alter table DEPARTMENT drop foreign key FK4F782F5273BAC72D;
alter table EMPLOYEE drop foreign key FK75C8D6AE88D2F58C;
alter table EMPLOYEE drop foreign key FK75C8D6AE73BAC72D;
alter table EMPLOYEE drop foreign key FK75C8D6AE94081E82;
alter table PERSON drop foreign key FK8C768F5528245721;
alter table PERSON drop foreign key FK8C768F55E40F34EC;
alter table PERSON drop foreign key FK8C768F554137CA3B;
alter table PROJECT drop foreign key FK185BD6F988D2F58C;
alter table PROJECT_PROJECT_MEMBERS drop foreign key FK14E9E46D157E048C;
alter table PROJECT_PROJECT_MEMBERS drop foreign key FK14E9E46D8D8F3B48;
drop table if exists CITY;
drop table if exists DEPARTMENT;
drop table if exists EMPLOYEE;
drop table if exists PERSON;
drop table if exists PROJECT;
drop table if exists PROJECT_PROJECT_MEMBERS;
create table CITY (ID varchar(36) not null, VERSION integer not null, ZIP varchar(5), COUNTRY varchar(255), NAME varchar(15) not null, CREATE_TIMESTAMP datetime, LAST_UPDATE_TIMESTAMP datetime, primary key (ID)) type=InnoDB;
create table DEPARTMENT (ID varchar(36) not null, VERSION integer not null, MANAGER_ID varchar(36), NAME varchar(15) not null, CREATE_TIMESTAMP datetime, LAST_UPDATE_TIMESTAMP datetime, DESCRIPTION text, primary key (ID)) type=InnoDB;
create table EMPLOYEE (ID varchar(36) not null, HIRE_DATE date, ANNUAL_SALARY integer, MANAGER_ID varchar(36), DEPARTMENT_ID varchar(36), primary key (ID)) type=InnoDB;
create table PERSON (ID varchar(36) not null, VERSION integer not null, BIRTH_DATE date, BIRTH_CITY_ID varchar(36), ADDRESS_CITY_ID varchar(36), MARRIED_TO_ID varchar(36) unique, GENDER varchar(255) not null, VEGETARIAN bit, NAME varchar(15) not null, CREATE_TIMESTAMP datetime, LAST_UPDATE_TIMESTAMP datetime, primary key (ID)) type=InnoDB;
create table PROJECT (ID varchar(36) not null, VERSION integer not null, DEPARTMENT_ID varchar(36), NAME varchar(15) not null, CREATE_TIMESTAMP datetime, LAST_UPDATE_TIMESTAMP datetime, primary key (ID)) type=InnoDB;
create table PROJECT_PROJECT_MEMBERS (EMPLOYEE_ID varchar(36) not null, PROJECT_ID varchar(36) not null, primary key (PROJECT_ID, EMPLOYEE_ID)) type=InnoDB;
alter table DEPARTMENT add index FK4F782F5273BAC72D (MANAGER_ID), add constraint FK4F782F5273BAC72D foreign key (MANAGER_ID) references EMPLOYEE (ID);
alter table EMPLOYEE add index FK75C8D6AE88D2F58C (DEPARTMENT_ID), add constraint FK75C8D6AE88D2F58C foreign key (DEPARTMENT_ID) references DEPARTMENT (ID);
alter table EMPLOYEE add index FK75C8D6AE73BAC72D (MANAGER_ID), add constraint FK75C8D6AE73BAC72D foreign key (MANAGER_ID) references EMPLOYEE (ID);
alter table EMPLOYEE add index FK75C8D6AE94081E82 (ID), add constraint FK75C8D6AE94081E82 foreign key (ID) references PERSON (ID);
alter table PERSON add index FK8C768F5528245721 (ADDRESS_CITY_ID), add constraint FK8C768F5528245721 foreign key (ADDRESS_CITY_ID) references CITY (ID);
alter table PERSON add index FK8C768F55E40F34EC (BIRTH_CITY_ID), add constraint FK8C768F55E40F34EC foreign key (BIRTH_CITY_ID) references CITY (ID);
alter table PERSON add index FK8C768F554137CA3B (MARRIED_TO_ID), add constraint FK8C768F554137CA3B foreign key (MARRIED_TO_ID) references PERSON (ID);
alter table PROJECT add index FK185BD6F988D2F58C (DEPARTMENT_ID), add constraint FK185BD6F988D2F58C foreign key (DEPARTMENT_ID) references DEPARTMENT (ID);
alter table PROJECT_PROJECT_MEMBERS add index FK14E9E46D157E048C (EMPLOYEE_ID), add constraint FK14E9E46D157E048C foreign key (EMPLOYEE_ID) references EMPLOYEE (ID);
alter table PROJECT_PROJECT_MEMBERS add index FK14E9E46D8D8F3B48 (PROJECT_ID), add constraint FK14E9E46D8D8F3B48 foreign key (PROJECT_ID) references PROJECT (ID);
