/*
 * Generated by Design2see. All rights reserved.
 */
package com.d2s.framework.sample.backend.domain;

/**
 * Nameable component.
 * <p>
 * Generated by Design2see. All rights reserved.
 * <p>
 * 
 * @author Generated by Design2see
 * @version $LastChangedRevision$
 */
public interface Nameable extends
    com.d2s.framework.sample.backend.domain.NameableService {

  /**
   * Gets the name.
   * 
   * @hibernate.property
   * @hibernate.column name = "NAME" length = "15" not-null = "true"
   * @return the name.
   */
  java.lang.String getName();

  /**
   * Sets the name.
   * 
   * @param name
   *            the name to set.
   */
  void setName(java.lang.String name);

}
