/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (AbstractIconFactory.as).
 */

package org.jspresso.framework.view {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.collections.IMap;

    [Bindable]
    public class AbstractIconFactoryBase implements IExternalizable, IIconFactory {

        private var _backwardIconUrl:String;
        private var _cancelIconImageURL:String;
        private var _errorIconImageURL:String;
        private var _forbiddenIconUrl:String;
        private var _forwardIconUrl:String;
        private var _iconStore:IMap;
        private var _infoIconImageURL:String;
        private var _noIconImageURL:String;
        private var _okYesIconImageURL:String;
        private var _warningIconImageURL:String;

        public function set backwardIconUrl(value:String):void {
            _backwardIconUrl = value;
        }

        public function set cancelIconImageURL(value:String):void {
            _cancelIconImageURL = value;
        }

        public function set errorIconImageURL(value:String):void {
            _errorIconImageURL = value;
        }

        public function set forbiddenIconUrl(value:String):void {
            _forbiddenIconUrl = value;
        }

        public function set forwardIconUrl(value:String):void {
            _forwardIconUrl = value;
        }

        public function set infoIconImageURL(value:String):void {
            _infoIconImageURL = value;
        }

        public function set noIconImageURL(value:String):void {
            _noIconImageURL = value;
        }

        public function set okYesIconImageURL(value:String):void {
            _okYesIconImageURL = value;
        }

        public function set warningIconImageURL(value:String):void {
            _warningIconImageURL = value;
        }

        public function readExternal(input:IDataInput):void {
            _backwardIconUrl = input.readObject() as String;
            _cancelIconImageURL = input.readObject() as String;
            _errorIconImageURL = input.readObject() as String;
            _forbiddenIconUrl = input.readObject() as String;
            _forwardIconUrl = input.readObject() as String;
            _iconStore = input.readObject() as IMap;
            _infoIconImageURL = input.readObject() as String;
            _noIconImageURL = input.readObject() as String;
            _okYesIconImageURL = input.readObject() as String;
            _warningIconImageURL = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_backwardIconUrl);
            output.writeObject(_cancelIconImageURL);
            output.writeObject(_errorIconImageURL);
            output.writeObject(_forbiddenIconUrl);
            output.writeObject(_forwardIconUrl);
            output.writeObject(_iconStore);
            output.writeObject(_infoIconImageURL);
            output.writeObject(_noIconImageURL);
            output.writeObject(_okYesIconImageURL);
            output.writeObject(_warningIconImageURL);
        }
    }
}