/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.jspresso.framework.view {

    import mx.collections.ListCollectionView;

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.view.BasicMapView")]
    public class BasicMapView extends BasicMapViewBase {

        override public function get children():ListCollectionView {
            // TODO: Gas3 default generated getter.
            return null;
        }
    }
}