/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicCompositeView.as).
 */

package org.jspresso.framework.view {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class BasicCompositeViewBase extends BasicView implements ICompositeView {

        private var _children:ListCollectionView;

        public function set children(value:ListCollectionView):void {
            _children = value;
        }
        public function get children():ListCollectionView {
            return _children;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _children = input.readObject() as ListCollectionView;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_children);
        }
    }
}