/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicMapView.as).
 */

package org.jspresso.framework.view {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ListCollectionView;
    
    import org.granite.collections.IMap;

    [Bindable]
    public class BasicMapViewBase extends BasicView implements IMapView {

        private var _childrenMap:IMap;

        public function set childrenMap(value:IMap):void {
            _childrenMap = value;
        }
        public function get childrenMap():IMap {
            return _childrenMap;
        }

        public function get children():ListCollectionView {
            return null;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _childrenMap = input.readObject() as IMap;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_childrenMap);
        }
    }
}