/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.jspresso.framework.view {

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.view.BasicView")]
    public class BasicView extends BasicViewBase {

        override public function get view():IView {
            // TODO: Gas3 default generated getter.
            return null;
        }
    }
}