/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (ICompositeView.as).
 */

package org.jspresso.framework.view {

    import mx.collections.ListCollectionView;

    public interface ICompositeViewBase extends IView {

        function get children():ListCollectionView;
    }
}