/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IView.as).
 */

package org.jspresso.framework.view {

    import org.jspresso.framework.binding.IValueConnector;
    import org.jspresso.framework.view.descriptor.IViewDescriptor;

    public interface IViewBase extends IViewProvider {

        function set connector(value:IValueConnector):void;
        function get connector():IValueConnector;

        function get descriptor():IViewDescriptor;

        function set parent(value:IView):void;
        function get parent():IView;

        function set peer(value:Object):void;
        function get peer():Object;
    }
}