/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (RComponent.as).
 */

package org.jspresso.framework.gui.remote {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.jspresso.framework.util.remote.RemoteServerPeer;

    [Bindable]
    public class RComponentBase extends RemoteServerPeer {

        private var _actions:ListCollectionView;
        private var _icon:RIcon;
        private var _label:String;
        private var _tooltip:String;

        public function set actions(value:ListCollectionView):void {
            _actions = value;
        }
        public function get actions():ListCollectionView {
            return _actions;
        }

        public function set icon(value:RIcon):void {
            _icon = value;
        }
        public function get icon():RIcon {
            return _icon;
        }

        public function set label(value:String):void {
            _label = value;
        }
        public function get label():String {
            return _label;
        }

        public function set tooltip(value:String):void {
            _tooltip = value;
        }
        public function get tooltip():String {
            return _tooltip;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _actions = input.readObject() as ListCollectionView;
            _icon = input.readObject() as RIcon;
            _label = input.readObject() as String;
            _tooltip = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_actions);
            output.writeObject(_icon);
            output.writeObject(_label);
            output.writeObject(_tooltip);
        }
    }
}