/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (REnumComponent.as).
 */

package org.jspresso.framework.gui.remote {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.collections.IMap;

    [Bindable]
    public class REnumComponentBase extends RComponent {

        private var _renderingIcons:IMap;
        private var _renderingTranslations:IMap;

        public function set renderingIcons(value:IMap):void {
            _renderingIcons = value;
        }
        public function get renderingIcons():IMap {
            return _renderingIcons;
        }

        public function set renderingTranslations(value:IMap):void {
            _renderingTranslations = value;
        }
        public function get renderingTranslations():IMap {
            return _renderingTranslations;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _renderingIcons = input.readObject() as IMap;
            _renderingTranslations = input.readObject() as IMap;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_renderingIcons);
            output.writeObject(_renderingTranslations);
        }
    }
}