/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (RIcon.as).
 */

package org.jspresso.framework.gui.remote {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.jspresso.framework.util.remote.RemoteServerPeer;

    [Bindable]
    public class RIconBase extends RemoteServerPeer {

        private var _height:int;
        private var _imageUrlSpec:String;
        private var _width:int;

        public function set height(value:int):void {
            _height = value;
        }
        public function get height():int {
            return _height;
        }

        public function set imageUrlSpec(value:String):void {
            _imageUrlSpec = value;
        }
        public function get imageUrlSpec():String {
            return _imageUrlSpec;
        }

        public function set width(value:int):void {
            _width = value;
        }
        public function get width():int {
            return _width;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _height = input.readObject() as int;
            _imageUrlSpec = input.readObject() as String;
            _width = input.readObject() as int;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_height);
            output.writeObject(_imageUrlSpec);
            output.writeObject(_width);
        }
    }
}