/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (RTableComponent.as).
 */

package org.jspresso.framework.gui.remote {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class RTableComponentBase extends RComponent {

        private var _columns:ListCollectionView;

        public function set columns(value:ListCollectionView):void {
            _columns = value;
        }
        public function get columns():ListCollectionView {
            return _columns;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _columns = input.readObject() as ListCollectionView;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_columns);
        }
    }
}