/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicEntityDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.entity.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.jspresso.framework.model.descriptor.basic.AbstractComponentDescriptor;

    [Bindable]
    public class BasicEntityDescriptorBase extends AbstractComponentDescriptor {

        private var _purelyAbstract:Boolean;

        public function set purelyAbstract(value:Boolean):void {
            _purelyAbstract = value;
        }
        override public function get purelyAbstract():Boolean {
            return _purelyAbstract;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _purelyAbstract = input.readObject() as Boolean;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_purelyAbstract);
        }
    }
}