/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.jspresso.framework.model.descriptor.basic {

    import mx.collections.ListCollectionView;

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.model.descriptor.basic.AbstractComponentDescriptor")]
    public class AbstractComponentDescriptor extends AbstractComponentDescriptorBase {

        override public function get computed():Boolean {
            // TODO: Gas3 default generated getter.
            return false;
        }

        override public function get declaredPropertyDescriptors():ListCollectionView {
            // TODO: Gas3 default generated getter.
            return null;
        }

        override public function get entity():Boolean {
            // TODO: Gas3 default generated getter.
            return false;
        }

        override public function get modelType():Class {
            // TODO: Gas3 default generated getter.
            return null;
        }

        override public function get propertyDescriptors():ListCollectionView {
            // TODO: Gas3 default generated getter.
            return null;
        }

        override public function get purelyAbstract():Boolean {
            // TODO: Gas3 default generated getter.
            return false;
        }

        override public function get queryComponentContract():Class {
            // TODO: Gas3 default generated getter.
            return null;
        }
    }
}