/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.jspresso.framework.model.descriptor.basic {

    import mx.collections.ListCollectionView;

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.model.descriptor.basic.AbstractEnumerationPropertyDescriptor")]
    public class AbstractEnumerationPropertyDescriptor extends AbstractEnumerationPropertyDescriptorBase {

        override public function get enumerationValues():ListCollectionView {
            // TODO: Gas3 default generated getter.
            return null;
        }

        override public function get translated():Boolean {
            // TODO: Gas3 default generated getter.
            return false;
        }
    }
}