/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (AbstractEnumerationPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.jspresso.framework.model.descriptor.IEnumerationPropertyDescriptor;

    [Bindable]
    public class AbstractEnumerationPropertyDescriptorBase extends BasicScalarPropertyDescriptor implements IEnumerationPropertyDescriptor {

        private var _enumerationName:String;
        private var _maxLength:Number;

        public function set enumerationName(value:String):void {
            _enumerationName = value;
        }
        public function get enumerationName():String {
            return _enumerationName;
        }

        public function set maxLength(value:Number):void {
            _maxLength = value;
        }
        public function get maxLength():Number {
            return _maxLength;
        }

        public function get enumerationValues():ListCollectionView {
            return null;
        }

        public function get translated():Boolean {
            return false;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _enumerationName = input.readObject() as String;
            _maxLength = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_enumerationName);
            output.writeObject(_maxLength);
        }
    }
}