/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicEnumerationPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.collections.IMap;

    [Bindable]
    public class BasicEnumerationPropertyDescriptorBase extends AbstractEnumerationPropertyDescriptor {

        private var _valuesAndIconImageUrls:IMap;

        public function set valuesAndIconImageUrls(value:IMap):void {
            _valuesAndIconImageUrls = value;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _valuesAndIconImageUrls = input.readObject() as IMap;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_valuesAndIconImageUrls);
        }
    }
}