/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicBinaryPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.collections.IMap;
    import org.jspresso.framework.model.descriptor.IBinaryPropertyDescriptor;

    [Bindable]
    public class BasicBinaryPropertyDescriptorBase extends BasicScalarPropertyDescriptor implements IBinaryPropertyDescriptor {

        private var _fileFilter:IMap;
        private var _maxLength:Number;

        public function set fileFilter(value:IMap):void {
            _fileFilter = value;
        }
        public function get fileFilter():IMap {
            return _fileFilter;
        }

        public function set maxLength(value:Number):void {
            _maxLength = value;
        }
        public function get maxLength():Number {
            return _maxLength;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _fileFilter = input.readObject() as IMap;
            _maxLength = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_fileFilter);
            output.writeObject(_maxLength);
        }
    }
}