/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicCollectionPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.jspresso.framework.model.descriptor.ICollectionDescriptor;
    import org.jspresso.framework.model.descriptor.ICollectionPropertyDescriptor;

    [Bindable]
    public class BasicCollectionPropertyDescriptorBase extends BasicRelationshipEndPropertyDescriptor implements ICollectionPropertyDescriptor {

        private var _manyToMany:Boolean;
        private var _orderingProperties:ListCollectionView;
        private var _referencedDescriptor:ICollectionDescriptor;

        public function set manyToMany(value:Boolean):void {
            _manyToMany = value;
        }
        public function get manyToMany():Boolean {
            return _manyToMany;
        }

        public function set orderingProperties(value:ListCollectionView):void {
            _orderingProperties = value;
        }
        public function get orderingProperties():ListCollectionView {
            return _orderingProperties;
        }

        public function set referencedDescriptor(value:ICollectionDescriptor):void {
            _referencedDescriptor = value;
        }
        public function get referencedDescriptor():ICollectionDescriptor {
            return _referencedDescriptor;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _manyToMany = input.readObject() as Boolean;
            _orderingProperties = input.readObject() as ListCollectionView;
            _referencedDescriptor = input.readObject() as ICollectionDescriptor;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_manyToMany);
            output.writeObject(_orderingProperties);
            output.writeObject(_referencedDescriptor);
        }
    }
}