/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicScalarPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.jspresso.framework.model.descriptor.IScalarPropertyDescriptor;

    [Bindable]
    public class BasicScalarPropertyDescriptorBase extends BasicPropertyDescriptor implements IScalarPropertyDescriptor {

        private var _defaultValue:Object;

        public function set defaultValue(value:Object):void {
            _defaultValue = value;
        }
        public function get defaultValue():Object {
            return _defaultValue;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _defaultValue = input.readObject() as Object;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_defaultValue);
        }
    }
}