/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicReferencePropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.collections.IMap;
    import org.jspresso.framework.model.descriptor.IComponentDescriptor;
    import org.jspresso.framework.model.descriptor.IReferencePropertyDescriptor;

    [Bindable]
    public class BasicReferencePropertyDescriptorBase extends BasicRelationshipEndPropertyDescriptor implements IReferencePropertyDescriptor {

        private var _initializationMapping:IMap;
        private var _referencedDescriptor:IComponentDescriptor;

        public function set initializationMapping(value:IMap):void {
            _initializationMapping = value;
        }
        public function get initializationMapping():IMap {
            return _initializationMapping;
        }

        public function set referencedDescriptor(value:IComponentDescriptor):void {
            _referencedDescriptor = value;
        }
        public function get referencedDescriptor():IComponentDescriptor {
            return _referencedDescriptor;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _initializationMapping = input.readObject() as IMap;
            _referencedDescriptor = input.readObject() as IComponentDescriptor;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_initializationMapping);
            output.writeObject(_referencedDescriptor);
        }
    }
}