/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicRelationshipEndPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.jspresso.framework.model.descriptor.IRelationshipEndPropertyDescriptor;

    [Bindable]
    public class BasicRelationshipEndPropertyDescriptorBase extends BasicPropertyDescriptor implements IRelationshipEndPropertyDescriptor {

        private var _composition:Boolean;
        private var _reverseRelationEnd:IRelationshipEndPropertyDescriptor;

        public function set composition(value:Boolean):void {
            _composition = value;
        }
        public function get composition():Boolean {
            return _composition;
        }

        public function set reverseRelationEnd(value:IRelationshipEndPropertyDescriptor):void {
            _reverseRelationEnd = value;
        }
        public function get reverseRelationEnd():IRelationshipEndPropertyDescriptor {
            return _reverseRelationEnd;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _composition = input.readObject() as Boolean;
            _reverseRelationEnd = input.readObject() as IRelationshipEndPropertyDescriptor;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_composition);
            output.writeObject(_reverseRelationEnd);
        }
    }
}