/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicTextPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.collections.IMap;
    import org.jspresso.framework.model.descriptor.ITextPropertyDescriptor;

    [Bindable]
    public class BasicTextPropertyDescriptorBase extends BasicStringPropertyDescriptor implements ITextPropertyDescriptor {

        private var _fileFilter:IMap;

        public function set fileFilter(value:IMap):void {
            _fileFilter = value;
        }
        public function get fileFilter():IMap {
            return _fileFilter;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _fileFilter = input.readObject() as IMap;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_fileFilter);
        }
    }
}