/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicQueryComponentDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.jspresso.framework.model.descriptor.IComponentDescriptor;

    [Bindable]
    public class BasicQueryComponentDescriptorBase extends AbstractComponentDescriptor {

        private var _componentDescriptor:IComponentDescriptor;

        public function get componentDescriptor():IComponentDescriptor {
            return _componentDescriptor;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _componentDescriptor = input.readObject() as IComponentDescriptor;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_componentDescriptor);
        }
    }
}