/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicCollectionDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.jspresso.framework.model.descriptor.ICollectionDescriptor;
    import org.jspresso.framework.model.descriptor.IComponentDescriptor;
    import org.jspresso.framework.util.descriptor.DefaultDescriptor;

    [Bindable]
    public class BasicCollectionDescriptorBase extends DefaultDescriptor implements ICollectionDescriptor {

        private var _collectionInterface:Class;
        private var _elementDescriptor:IComponentDescriptor;

        public function set collectionInterface(value:Class):void {
            _collectionInterface = value;
        }
        public function get collectionInterface():Class {
            return _collectionInterface;
        }

        public function set elementDescriptor(value:IComponentDescriptor):void {
            _elementDescriptor = value;
        }
        public function get elementDescriptor():IComponentDescriptor {
            return _elementDescriptor;
        }

        public function get modelType():Class {
            return null;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _collectionInterface = input.readObject() as Class;
            _elementDescriptor = input.readObject() as IComponentDescriptor;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_collectionInterface);
            output.writeObject(_elementDescriptor);
        }
    }
}