/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicInterfaceDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class BasicInterfaceDescriptorBase extends AbstractComponentDescriptor {

        private var _computed:Boolean;

        public function set computed(value:Boolean):void {
            _computed = value;
        }
        override public function get computed():Boolean {
            return _computed;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _computed = input.readObject() as Boolean;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_computed);
        }
    }
}