/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicDecimalPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.jspresso.framework.model.descriptor.IDecimalPropertyDescriptor;

    [Bindable]
    public class BasicDecimalPropertyDescriptorBase extends BasicNumberPropertyDescriptor implements IDecimalPropertyDescriptor {

        private var _maxFractionDigit:Number;

        public function set maxFractionDigit(value:Number):void {
            _maxFractionDigit = value;
        }
        public function get maxFractionDigit():Number {
            return _maxFractionDigit;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _maxFractionDigit = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_maxFractionDigit);
        }
    }
}