/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.jspresso.framework.model.descriptor.basic {

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.model.descriptor.basic.BasicPropertyDescriptor")]
    public class BasicPropertyDescriptor extends BasicPropertyDescriptorBase {

        override public function get modelType():Class {
            // TODO: Gas3 default generated getter.
            return null;
        }

        override public function get modifiable():Boolean {
            // TODO: Gas3 default generated getter.
            return false;
        }

        override public function get overload():Boolean {
            // TODO: Gas3 default generated getter.
            return false;
        }

        override public function get queryable():Boolean {
            // TODO: Gas3 default generated getter.
            return false;
        }
    }
}