/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicDurationPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.jspresso.framework.model.descriptor.IDurationPropertyDescriptor;

    [Bindable]
    public class BasicDurationPropertyDescriptorBase extends BasicScalarPropertyDescriptor implements IDurationPropertyDescriptor {

        private var _maxMillis:Number;

        public function set maxMillis(value:Number):void {
            _maxMillis = value;
        }
        public function get maxMillis():Number {
            return _maxMillis;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _maxMillis = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_maxMillis);
        }
    }
}