/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicNumberPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.jspresso.framework.model.descriptor.INumberPropertyDescriptor;

    [Bindable]
    public class BasicNumberPropertyDescriptorBase extends BasicScalarPropertyDescriptor implements INumberPropertyDescriptor {

        private var _maxValue:Number;
        private var _minValue:Number;

        public function set maxValue(value:Number):void {
            _maxValue = value;
        }
        public function get maxValue():Number {
            return _maxValue;
        }

        public function set minValue(value:Number):void {
            _minValue = value;
        }
        public function get minValue():Number {
            return _minValue;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _maxValue = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _minValue = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_maxValue);
            output.writeObject(_minValue);
        }
    }
}