/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicDatePropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.util.Enum;
    import org.jspresso.framework.model.descriptor.EDateType;
    import org.jspresso.framework.model.descriptor.IDatePropertyDescriptor;

    [Bindable]
    public class BasicDatePropertyDescriptorBase extends BasicScalarPropertyDescriptor implements IDatePropertyDescriptor {

        private var _type:EDateType;

        public function set type(value:EDateType):void {
            _type = value;
        }
        public function get type():EDateType {
            return _type;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _type = Enum.readEnum(input) as EDateType;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_type);
        }
    }
}