/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicIntegerPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.jspresso.framework.model.descriptor.IIntegerPropertyDescriptor;

    [Bindable]
    public class BasicIntegerPropertyDescriptorBase extends BasicNumberPropertyDescriptor implements IIntegerPropertyDescriptor {


        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
        }
    }
}