/*
 * Generated by Design2see. All rights reserved.
 */
package com.d2s.framework.sample.backend.domain;

/**
 * Describeable component.
 * <p>
 * Generated by Design2see. All rights reserved.
 * <p>
 * 
 * @author Generated by Design2see
 */
public interface Describeable {

  /**
   * Gets the description.
   * 
   * @hibernate.property
   * @hibernate.column name = "DESCRIPTION" length = "256"
   * @return the description.
   */
  java.lang.String getDescription();

  /**
   * Sets the description.
   * 
   * @param description
   *          the description to set.
   */
  void setDescription(java.lang.String description);

}
