/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.jspresso.framework.view.descriptor {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.view.descriptor.EAxis")]
    public class EAxis extends Enum {

        public static const ROW:EAxis = new EAxis("ROW", _);
        public static const COLUMN:EAxis = new EAxis("COLUMN", _);

        function EAxis(value:String = null, restrictor:* = null) {
            super((value || ROW.name), restrictor);
        }
        
        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [ROW, COLUMN];
        }

        public static function valueOf(name:String):EAxis {
        	return EAxis(ROW.constantOf(name));
        }
    }
}