/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.jspresso.framework.view.descriptor {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.view.descriptor.EBorderType")]
    public class EBorderType extends Enum {

        public static const NONE:EBorderType = new EBorderType("NONE", _);
        public static const SIMPLE:EBorderType = new EBorderType("SIMPLE", _);
        public static const TITLED:EBorderType = new EBorderType("TITLED", _);

        function EBorderType(value:String = null, restrictor:* = null) {
            super((value || NONE.name), restrictor);
        }
        
        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [NONE, SIMPLE, TITLED];
        }

        public static function valueOf(name:String):EBorderType {
        	return EBorderType(NONE.constantOf(name));
        }
    }
}