/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.jspresso.framework.view.descriptor {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.view.descriptor.ELabelPosition")]
    public class ELabelPosition extends Enum {

        public static const ASIDE:ELabelPosition = new ELabelPosition("ASIDE", _);
        public static const ABOVE:ELabelPosition = new ELabelPosition("ABOVE", _);

        function ELabelPosition(value:String = null, restrictor:* = null) {
            super((value || ASIDE.name), restrictor);
        }
        
        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [ASIDE, ABOVE];
        }

        public static function valueOf(name:String):ELabelPosition {
        	return ELabelPosition(ASIDE.constantOf(name));
        }
    }
}