/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.jspresso.framework.view.descriptor {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.view.descriptor.EOrientation")]
    public class EOrientation extends Enum {

        public static const VERTICAL:EOrientation = new EOrientation("VERTICAL", _);
        public static const HORIZONTAL:EOrientation = new EOrientation("HORIZONTAL", _);

        function EOrientation(value:String = null, restrictor:* = null) {
            super((value || VERTICAL.name), restrictor);
        }
        
        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [VERTICAL, HORIZONTAL];
        }

        public static function valueOf(name:String):EOrientation {
        	return EOrientation(VERTICAL.constantOf(name));
        }
    }
}