/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IBorderViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor {

    public interface IBorderViewDescriptorBase extends ICompositeViewDescriptor {

        function get centerViewDescriptor():IViewDescriptor;

        function get eastViewDescriptor():IViewDescriptor;

        function get northViewDescriptor():IViewDescriptor;

        function get southViewDescriptor():IViewDescriptor;

        function get westViewDescriptor():IViewDescriptor;
    }
}