/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (ICardViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor {

    import org.granite.collections.IMap;

    public interface ICardViewDescriptorBase extends IViewDescriptor {

        function get cardViewDescriptors():IMap;
    }
}