/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IComponentViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor {

    import mx.collections.ListCollectionView;

    public interface IComponentViewDescriptorBase extends IViewDescriptor {

        function get columnCount():int;

        function get labelsPosition():ELabelPosition;

        function get propertyViewDescriptors():ListCollectionView;
    }
}