/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IEvenGridViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor {

    public interface IEvenGridViewDescriptorBase extends IGridViewDescriptor {

        function get drivingDimension():EAxis;

        function get drivingDimensionCellCount():int;
    }
}