/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (ISubViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor {

    import mx.collections.ListCollectionView;
    import org.jspresso.framework.model.descriptor.IModelDescriptor;
    import org.jspresso.framework.util.descriptor.IIconDescriptor;

    public interface ISubViewDescriptorBase extends IIconDescriptor {

        function set grantedRoles(value:ListCollectionView):void;

        function get modelDescriptor():IModelDescriptor;

        function get readOnly():Boolean;

        function get readabilityGates():ListCollectionView;

        function get writabilityGates():ListCollectionView;
    }
}