/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor {

    import org.jspresso.framework.view.action.IActionable;

    public interface IViewDescriptorBase extends ISubViewDescriptor, IActionable {

        function get background():String;

        function get borderType():EBorderType;

        function get font():String;

        function get foreground():String;
    }
}