/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (ViewConstraints.as).
 */

package org.jspresso.framework.view.descriptor {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class ViewConstraintsBase implements IExternalizable {

        private var _column:int;
        private var _height:int;
        private var _heightResizable:Boolean;
        private var _row:int;
        private var _width:int;
        private var _widthResizable:Boolean;

        public function set column(value:int):void {
            _column = value;
        }
        public function get column():int {
            return _column;
        }

        public function set height(value:int):void {
            _height = value;
        }
        public function get height():int {
            return _height;
        }

        public function set heightResizable(value:Boolean):void {
            _heightResizable = value;
        }
        public function get heightResizable():Boolean {
            return _heightResizable;
        }

        public function set row(value:int):void {
            _row = value;
        }
        public function get row():int {
            return _row;
        }

        public function set width(value:int):void {
            _width = value;
        }
        public function get width():int {
            return _width;
        }

        public function set widthResizable(value:Boolean):void {
            _widthResizable = value;
        }
        public function get widthResizable():Boolean {
            return _widthResizable;
        }

        public function readExternal(input:IDataInput):void {
            _column = input.readObject() as int;
            _height = input.readObject() as int;
            _heightResizable = input.readObject() as Boolean;
            _row = input.readObject() as int;
            _width = input.readObject() as int;
            _widthResizable = input.readObject() as Boolean;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_column);
            output.writeObject(_height);
            output.writeObject(_heightResizable);
            output.writeObject(_row);
            output.writeObject(_width);
            output.writeObject(_widthResizable);
        }
    }
}