/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (ICompositeValueConnector.as).
 */

package org.jspresso.framework.binding {

    import mx.collections.ListCollectionView;

    public interface ICompositeValueConnectorBase extends IValueConnector {

        function get childConnectorCount():int;

        function get childConnectorKeys():ListCollectionView;
    }
}