/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IConnector.as).
 */

package org.jspresso.framework.binding {

    public interface IConnectorBase {

        function set id(value:String):void;
        function get id():String;
    }
}