/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IRenderableCompositeValueConnector.as).
 */

package org.jspresso.framework.binding {

    public interface IRenderableCompositeValueConnectorBase extends ICompositeValueConnector {

        function get displayDescription():String;

        function get displayIconImageUrl():String;

        function get displayValue():String;

        function get renderingConnector():IValueConnector;
    }
}