/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IValueConnector.as).
 */

package org.jspresso.framework.binding {

    public interface IValueConnectorBase extends IConnector {

        function get connectorPath():String;

        function set connectorValue(value:Object):void;
        function get connectorValue():Object;

        function set locallyReadable(value:Boolean):void;

        function set locallyWritable(value:Boolean):void;

        function set modelConnector(value:IValueConnector):void;
        function get modelConnector():IValueConnector;

        function set parentConnector(value:ICompositeValueConnector):void;
        function get parentConnector():ICompositeValueConnector;

        function get readable():Boolean;

        function get writable():Boolean;
    }
}