/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.jspresso.framework.model.descriptor.query {

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.model.descriptor.query.ComparableQueryStructureDescriptor")]
    public class ComparableQueryStructureDescriptor extends ComparableQueryStructureDescriptorBase {
    }
}