/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (RemoteCollectionConnector.as).
 */

package org.jspresso.framework.binding.remote {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.jspresso.framework.util.remote.IRemoteServerPeer;

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.binding.remote.RemoteCollectionConnector")]
    public class RemoteCollectionConnector implements IExternalizable, IRemoteServerPeer {

        private var _selectedIndices:Array;
        private var _uid:String;

        public function set selectedIndices(value:Array):void {
            _selectedIndices = value;
        }
        public function get selectedIndices():Array {
            return _selectedIndices;
        }

        public function set uid(value:String):void {
            _uid = value;
        }
        public function get uid():String {
            return _uid;
        }

        public function readExternal(input:IDataInput):void {
            _selectedIndices = input.readObject() as Array;
            _uid = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_selectedIndices);
            output.writeObject(_uid);
        }
    }
}