/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (RemoteCollectionConnectorListProvider.as).
 */

package org.jspresso.framework.binding.remote {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;
    import org.jspresso.framework.util.remote.IRemoteServerPeer;

    [Bindable]
    public class RemoteCollectionConnectorListProviderBase implements IExternalizable, IRemoteServerPeer {

        private var _collectionConnectors:ListCollectionView;
        private var _uid:String;

        public function set collectionConnectors(value:ListCollectionView):void {
            _collectionConnectors = value;
        }
        public function get collectionConnectors():ListCollectionView {
            return _collectionConnectors;
        }

        public function set uid(value:String):void {
            _uid = value;
        }
        public function get uid():String {
            return _uid;
        }

        public function readExternal(input:IDataInput):void {
            _collectionConnectors = input.readObject() as ListCollectionView;
            _uid = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_collectionConnectors);
            output.writeObject(_uid);
        }
    }
}