/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (RemoteCollectionConnector.as).
 */

package org.jspresso.framework.binding.remote {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    
    import org.jspresso.framework.binding.ICollectionConnector;
    import org.jspresso.framework.util.remote.IRemoteClientPeer;

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.binding.remote.RemoteCollectionConnector")]
    public class RemoteCollectionConnector extends RemoteCompositeConnector implements ICollectionConnector, IExternalizable, IRemoteClientPeer {

        private var _selectedIndices:Array;

        public function set selectedIndices(value:Array):void {
            _selectedIndices = value;
        }
        public function get selectedIndices():Array {
            return _selectedIndices;
        }

        override public function readExternal(input:IDataInput):void {
            _selectedIndices = input.readObject() as Array;
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(_selectedIndices);
        }
    }
}