/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (RemoteCollectionConnectorListProvider.as).
 */

package org.jspresso.framework.binding.remote {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    
    import mx.collections.ListCollectionView;
    
    import org.jspresso.framework.binding.ICollectionConnectorListProvider;
    import org.jspresso.framework.util.remote.IRemoteClientPeer;

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.binding.remote.RemoteCollectionConnectorListProvider")]
    public class RemoteCollectionConnectorListProvider extends RemoteCompositeConnector implements ICollectionConnectorListProvider, IExternalizable, IRemoteClientPeer {

        private var _collectionConnectors:ListCollectionView;

        public function set collectionConnectors(value:ListCollectionView):void {
            _collectionConnectors = value;
        }
        public function get collectionConnectors():ListCollectionView {
            return _collectionConnectors;
        }


        override public function readExternal(input:IDataInput):void {
            _collectionConnectors = input.readObject() as ListCollectionView;
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(_collectionConnectors);
        }
    }
}