/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (RemoteCompositeConnector.as).
 */

package org.jspresso.framework.binding.remote {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    
    import mx.collections.ListCollectionView;
    
    import org.jspresso.framework.binding.ICompositeValueConnector;
    import org.jspresso.framework.util.remote.IRemoteClientPeer;

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.binding.remote.RemoteCompositeConnector")]
    public class RemoteCompositeConnector extends RemoteValueConnector implements ICompositeValueConnector, IExternalizable, IRemoteClientPeer {

        private var _children:ListCollectionView;

        public function set children(value:ListCollectionView):void {
            _children = value;
        }
        public function get children():ListCollectionView {
            return _children;
        }

        override public function readExternal(input:IDataInput):void {
            _children = input.readObject() as ListCollectionView;
        }

        override public function writeExternal(output:IDataOutput):void {
            output.writeObject(_children);
        }
    }
}