/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IRemoteServerPeer.as).
 */

package org.jspresso.framework.util.remote {

    public interface IRemoteServerPeerBase {

        function get uid():String;
    }
}