/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (RemoteServerPeer.as).
 */

package org.jspresso.framework.util.remote {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class RemoteServerPeerBase implements IExternalizable, IRemoteServerPeer {

        private var _uid:String;

        public function get uid():String {
            return _uid;
        }

        public function readExternal(input:IDataInput):void {
            _uid = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_uid);
        }
    }
}