/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (DefaultIconDescriptor.as).
 */

package org.jspresso.framework.util.descriptor {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class DefaultIconDescriptorBase extends DefaultDescriptor implements IIconDescriptor {

        private var _iconImageURL:String;

        public function set iconImageURL(value:String):void {
            _iconImageURL = value;
        }
        public function get iconImageURL():String {
            return _iconImageURL;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _iconImageURL = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_iconImageURL);
        }
    }
}