/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (DefaultDescriptor.as).
 */

package org.jspresso.framework.util.descriptor {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class DefaultDescriptorBase implements IExternalizable, IDescriptor {

        private var _description:String;
        private var _i18nNameKey:String;
        private var _name:String;

        public function set description(value:String):void {
            _description = value;
        }
        public function get description():String {
            return _description;
        }

        public function set i18nNameKey(value:String):void {
            _i18nNameKey = value;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function readExternal(input:IDataInput):void {
            _description = input.readObject() as String;
            _i18nNameKey = input.readObject() as String;
            _name = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_description);
            output.writeObject(_i18nNameKey);
            output.writeObject(_name);
        }
    }
}