/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IIconDescriptor.as).
 */

package org.jspresso.framework.util.descriptor {

    public interface IIconDescriptorBase extends IDescriptor {

        function get iconImageURL():String;
    }
}