/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (ActionMap.as).
 */

package org.jspresso.framework.view.action {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class ActionMapBase implements IExternalizable {

        private var _actionLists:ListCollectionView;
        private var _parentActionMaps:ListCollectionView;

        public function set actionLists(value:ListCollectionView):void {
            _actionLists = value;
        }
        public function get actionLists():ListCollectionView {
            return _actionLists;
        }

        public function set parentActionMaps(value:ListCollectionView):void {
            _parentActionMaps = value;
        }

        public function readExternal(input:IDataInput):void {
            _actionLists = input.readObject() as ListCollectionView;
            _parentActionMaps = input.readObject() as ListCollectionView;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_actionLists);
            output.writeObject(_parentActionMaps);
        }
    }
}