/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (ActionList.as).
 */

package org.jspresso.framework.view.action {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.jspresso.framework.util.descriptor.DefaultIconDescriptor;

    [Bindable]
    public class ActionListBase extends DefaultIconDescriptor {

        private var _actions:ListCollectionView;

        public function set actions(value:ListCollectionView):void {
            _actions = value;
        }
        public function get actions():ListCollectionView {
            return _actions;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _actions = input.readObject() as ListCollectionView;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_actions);
        }
    }
}