/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IDisplayableAction.as).
 */

package org.jspresso.framework.view.action {

    import mx.collections.ListCollectionView;
    import org.jspresso.framework.util.descriptor.IIconDescriptor;

    public interface IDisplayableActionBase extends IIconDescriptor {

        function get acceleratorAsString():String;

        function get actionabilityGates():ListCollectionView;

        function get mnemonicAsString():String;
    }
}