/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicValueConnector.as).
 */

package org.jspresso.framework.binding.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class BasicValueConnectorBase implements IExternalizable {

        private var _connecteeValue:Object;

        public function readExternal(input:IDataInput):void {
            _connecteeValue = input.readObject() as Object;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_connecteeValue);
        }
    }
}