/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicEvenGridViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.granite.util.Enum;
    import org.jspresso.framework.view.descriptor.EAxis;
    import org.jspresso.framework.view.descriptor.IEvenGridViewDescriptor;

    [Bindable]
    public class BasicEvenGridViewDescriptorBase extends BasicCompositeViewDescriptor implements IEvenGridViewDescriptor {

        private var _childViewDescriptors:ListCollectionView;
        private var _drivingDimension:EAxis;
        private var _drivingDimensionCellCount:int;

        public function set childViewDescriptors(value:ListCollectionView):void {
            _childViewDescriptors = value;
        }
        override public function get childViewDescriptors():ListCollectionView {
            return _childViewDescriptors;
        }

        public function set drivingDimension(value:EAxis):void {
            _drivingDimension = value;
        }
        public function get drivingDimension():EAxis {
            return _drivingDimension;
        }

        public function set drivingDimensionCellCount(value:int):void {
            _drivingDimensionCellCount = value;
        }
        public function get drivingDimensionCellCount():int {
            return _drivingDimensionCellCount;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _childViewDescriptors = input.readObject() as ListCollectionView;
            _drivingDimension = Enum.readEnum(input) as EAxis;
            _drivingDimensionCellCount = input.readObject() as int;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_childViewDescriptors);
            output.writeObject(_drivingDimension);
            output.writeObject(_drivingDimensionCellCount);
        }
    }
}