/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicComponentViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.granite.collections.IMap;
    import org.granite.util.Enum;
    import org.jspresso.framework.view.descriptor.ELabelPosition;
    import org.jspresso.framework.view.descriptor.IComponentViewDescriptor;

    [Bindable]
    public class BasicComponentViewDescriptorBase extends BasicViewDescriptor implements IComponentViewDescriptor {

        private var _columnCount:int;
        private var _labelsPosition:ELabelPosition;
        private var _propertyViewDescriptors:ListCollectionView;
        private var _propertyWidths:IMap;
        private var _renderedChildProperties:IMap;

        public function set columnCount(value:int):void {
            _columnCount = value;
        }
        public function get columnCount():int {
            return _columnCount;
        }

        public function set labelsPosition(value:ELabelPosition):void {
            _labelsPosition = value;
        }
        public function get labelsPosition():ELabelPosition {
            return _labelsPosition;
        }

        public function set propertyViewDescriptors(value:ListCollectionView):void {
            _propertyViewDescriptors = value;
        }
        public function get propertyViewDescriptors():ListCollectionView {
            return _propertyViewDescriptors;
        }

        public function set propertyWidths(value:IMap):void {
            _propertyWidths = value;
        }

        public function set renderedChildProperties(value:IMap):void {
            _renderedChildProperties = value;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _columnCount = input.readObject() as int;
            _labelsPosition = Enum.readEnum(input) as ELabelPosition;
            _propertyViewDescriptors = input.readObject() as ListCollectionView;
            _propertyWidths = input.readObject() as IMap;
            _renderedChildProperties = input.readObject() as IMap;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_columnCount);
            output.writeObject(_labelsPosition);
            output.writeObject(_propertyViewDescriptors);
            output.writeObject(_propertyWidths);
            output.writeObject(_renderedChildProperties);
        }
    }
}