/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.util.Enum;
    import org.jspresso.framework.view.action.ActionMap;
    import org.jspresso.framework.view.descriptor.EBorderType;
    import org.jspresso.framework.view.descriptor.IViewDescriptor;

    [Bindable]
    public class BasicViewDescriptorBase extends BasicSubviewDescriptor implements IViewDescriptor {

        private var _actionMap:ActionMap;
        private var _background:String;
        private var _borderType:EBorderType;
        private var _font:String;
        private var _foreground:String;

        public function set actionMap(value:ActionMap):void {
            _actionMap = value;
        }
        public function get actionMap():ActionMap {
            return _actionMap;
        }

        public function set background(value:String):void {
            _background = value;
        }
        public function get background():String {
            return _background;
        }

        public function set borderType(value:EBorderType):void {
            _borderType = value;
        }
        public function get borderType():EBorderType {
            return _borderType;
        }

        public function set font(value:String):void {
            _font = value;
        }
        public function get font():String {
            return _font;
        }

        public function set foreground(value:String):void {
            _foreground = value;
        }
        public function get foreground():String {
            return _foreground;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _actionMap = input.readObject() as ActionMap;
            _background = input.readObject() as String;
            _borderType = Enum.readEnum(input) as EBorderType;
            _font = input.readObject() as String;
            _foreground = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_actionMap);
            output.writeObject(_background);
            output.writeObject(_borderType);
            output.writeObject(_font);
            output.writeObject(_foreground);
        }
    }
}