/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicTreeViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.jspresso.framework.util.IIconImageURLProvider;
    import org.jspresso.framework.view.descriptor.ITreeLevelDescriptor;
    import org.jspresso.framework.view.descriptor.ITreeViewDescriptor;

    [Bindable]
    public class BasicTreeViewDescriptorBase extends BasicViewDescriptor implements ITreeViewDescriptor {

        private var _childDescriptor:ITreeLevelDescriptor;
        private var _iconImageURLProvider:IIconImageURLProvider;
        private var _maxDepth:int;
        private var _renderedProperty:String;
        private var _rootSubtreeDescriptor:ITreeLevelDescriptor;

        public function set childDescriptor(value:ITreeLevelDescriptor):void {
            _childDescriptor = value;
        }

        public function set iconImageURLProvider(value:IIconImageURLProvider):void {
            _iconImageURLProvider = value;
        }

        public function set maxDepth(value:int):void {
            _maxDepth = value;
        }
        public function get maxDepth():int {
            return _maxDepth;
        }

        public function set renderedProperty(value:String):void {
            _renderedProperty = value;
        }

        public function set rootSubtreeDescriptor(value:ITreeLevelDescriptor):void {
            _rootSubtreeDescriptor = value;
        }
        public function get rootSubtreeDescriptor():ITreeLevelDescriptor {
            return _rootSubtreeDescriptor;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _childDescriptor = input.readObject() as ITreeLevelDescriptor;
            _iconImageURLProvider = input.readObject() as IIconImageURLProvider;
            _maxDepth = input.readObject() as int;
            _renderedProperty = input.readObject() as String;
            _rootSubtreeDescriptor = input.readObject() as ITreeLevelDescriptor;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_childDescriptor);
            output.writeObject(_iconImageURLProvider);
            output.writeObject(_maxDepth);
            output.writeObject(_renderedProperty);
            output.writeObject(_rootSubtreeDescriptor);
        }
    }
}