/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicListViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.jspresso.framework.view.descriptor.IListViewDescriptor;

    [Bindable]
    public class BasicListViewDescriptorBase extends BasicCollectionViewDescriptor implements IListViewDescriptor {

        private var _renderedProperty:String;

        public function set renderedProperty(value:String):void {
            _renderedProperty = value;
        }
        public function get renderedProperty():String {
            return _renderedProperty;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _renderedProperty = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_renderedProperty);
        }
    }
}