/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicConstrainedGridViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.collections.IMap;
    import org.jspresso.framework.view.descriptor.IConstrainedGridViewDescriptor;

    [Bindable]
    public class BasicConstrainedGridViewDescriptorBase extends BasicCompositeViewDescriptor implements IConstrainedGridViewDescriptor {

        private var _constrainedViews:IMap;

        public function set constrainedViews(value:IMap):void {
            _constrainedViews = value;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _constrainedViews = input.readObject() as IMap;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_constrainedViews);
        }
    }
}