/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicSubviewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.jspresso.framework.model.descriptor.IModelDescriptor;
    import org.jspresso.framework.util.descriptor.DefaultIconDescriptor;
    import org.jspresso.framework.view.descriptor.ISubViewDescriptor;

    [Bindable]
    public class BasicSubviewDescriptorBase extends DefaultIconDescriptor implements ISubViewDescriptor {

        private var _grantedRoles:ListCollectionView;
        private var _modelDescriptor:IModelDescriptor;
        private var _readOnly:Boolean;
        private var _readabilityGates:ListCollectionView;
        private var _writabilityGates:ListCollectionView;

        public function set grantedRoles(value:ListCollectionView):void {
            _grantedRoles = value;
        }
        public function get grantedRoles():ListCollectionView {
            return _grantedRoles;
        }

        public function set modelDescriptor(value:IModelDescriptor):void {
            _modelDescriptor = value;
        }
        public function get modelDescriptor():IModelDescriptor {
            return _modelDescriptor;
        }

        public function set readOnly(value:Boolean):void {
            _readOnly = value;
        }
        public function get readOnly():Boolean {
            return _readOnly;
        }

        public function set readabilityGates(value:ListCollectionView):void {
            _readabilityGates = value;
        }
        public function get readabilityGates():ListCollectionView {
            return _readabilityGates;
        }

        public function set writabilityGates(value:ListCollectionView):void {
            _writabilityGates = value;
        }
        public function get writabilityGates():ListCollectionView {
            return _writabilityGates;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _grantedRoles = input.readObject() as ListCollectionView;
            _modelDescriptor = input.readObject() as IModelDescriptor;
            _readOnly = input.readObject() as Boolean;
            _readabilityGates = input.readObject() as ListCollectionView;
            _writabilityGates = input.readObject() as ListCollectionView;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_grantedRoles);
            output.writeObject(_modelDescriptor);
            output.writeObject(_readOnly);
            output.writeObject(_readabilityGates);
            output.writeObject(_writabilityGates);
        }
    }
}