/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicNestingViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.jspresso.framework.view.descriptor.INestingViewDescriptor;
    import org.jspresso.framework.view.descriptor.IViewDescriptor;

    [Bindable]
    public class BasicNestingViewDescriptorBase extends BasicViewDescriptor implements INestingViewDescriptor {

        private var _nestedViewDescriptor:IViewDescriptor;

        public function set nestedViewDescriptor(value:IViewDescriptor):void {
            _nestedViewDescriptor = value;
        }
        public function get nestedViewDescriptor():IViewDescriptor {
            return _nestedViewDescriptor;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _nestedViewDescriptor = input.readObject() as IViewDescriptor;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_nestedViewDescriptor);
        }
    }
}