/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicCompositeViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.jspresso.framework.view.descriptor.ICompositeViewDescriptor;

    [Bindable]
    public class BasicCompositeViewDescriptorBase extends BasicViewDescriptor implements ICompositeViewDescriptor {

        private var _cascadingModels:Boolean;

        public function set cascadingModels(value:Boolean):void {
            _cascadingModels = value;
        }
        public function get cascadingModels():Boolean {
            return _cascadingModels;
        }

        public function get childViewDescriptors():ListCollectionView {
            return null;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _cascadingModels = input.readObject() as Boolean;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_cascadingModels);
        }
    }
}