/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicTableViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.jspresso.framework.view.descriptor.ITableViewDescriptor;

    [Bindable]
    public class BasicTableViewDescriptorBase extends BasicCollectionViewDescriptor implements ITableViewDescriptor {

        private var _columnViewDescriptors:ListCollectionView;

        public function set columnViewDescriptors(value:ListCollectionView):void {
            _columnViewDescriptors = value;
        }
        public function get columnViewDescriptors():ListCollectionView {
            return _columnViewDescriptors;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _columnViewDescriptors = input.readObject() as ListCollectionView;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_columnViewDescriptors);
        }
    }
}