/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicPropertyViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.jspresso.framework.view.descriptor.IPropertyViewDescriptor;

    [Bindable]
    public class BasicPropertyViewDescriptorBase extends BasicViewDescriptor implements IPropertyViewDescriptor {

        private var _renderedChildProperties:ListCollectionView;

        public function set renderedChildProperties(value:ListCollectionView):void {
            _renderedChildProperties = value;
        }
        public function get renderedChildProperties():ListCollectionView {
            return _renderedChildProperties;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _renderedChildProperties = input.readObject() as ListCollectionView;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_renderedChildProperties);
        }
    }
}