/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicTabViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.jspresso.framework.view.descriptor.ITabViewDescriptor;

    [Bindable]
    public class BasicTabViewDescriptorBase extends BasicCompositeViewDescriptor implements ITabViewDescriptor {

        private var _viewDescriptors:ListCollectionView;

        public function set viewDescriptors(value:ListCollectionView):void {
            _viewDescriptors = value;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _viewDescriptors = input.readObject() as ListCollectionView;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_viewDescriptors);
        }
    }
}