/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (BasicBorderViewDescriptor.as).
 */

package org.jspresso.framework.view.descriptor.basic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.jspresso.framework.view.descriptor.IBorderViewDescriptor;
    import org.jspresso.framework.view.descriptor.IViewDescriptor;

    [Bindable]
    public class BasicBorderViewDescriptorBase extends BasicCompositeViewDescriptor implements IBorderViewDescriptor {

        private var _centerViewDescriptor:IViewDescriptor;
        private var _eastViewDescriptor:IViewDescriptor;
        private var _northViewDescriptor:IViewDescriptor;
        private var _southViewDescriptor:IViewDescriptor;
        private var _westViewDescriptor:IViewDescriptor;

        public function set centerViewDescriptor(value:IViewDescriptor):void {
            _centerViewDescriptor = value;
        }
        public function get centerViewDescriptor():IViewDescriptor {
            return _centerViewDescriptor;
        }

        public function set eastViewDescriptor(value:IViewDescriptor):void {
            _eastViewDescriptor = value;
        }
        public function get eastViewDescriptor():IViewDescriptor {
            return _eastViewDescriptor;
        }

        public function set northViewDescriptor(value:IViewDescriptor):void {
            _northViewDescriptor = value;
        }
        public function get northViewDescriptor():IViewDescriptor {
            return _northViewDescriptor;
        }

        public function set southViewDescriptor(value:IViewDescriptor):void {
            _southViewDescriptor = value;
        }
        public function get southViewDescriptor():IViewDescriptor {
            return _southViewDescriptor;
        }

        public function set westViewDescriptor(value:IViewDescriptor):void {
            _westViewDescriptor = value;
        }
        public function get westViewDescriptor():IViewDescriptor {
            return _westViewDescriptor;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _centerViewDescriptor = input.readObject() as IViewDescriptor;
            _eastViewDescriptor = input.readObject() as IViewDescriptor;
            _northViewDescriptor = input.readObject() as IViewDescriptor;
            _southViewDescriptor = input.readObject() as IViewDescriptor;
            _westViewDescriptor = input.readObject() as IViewDescriptor;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_centerViewDescriptor);
            output.writeObject(_eastViewDescriptor);
            output.writeObject(_northViewDescriptor);
            output.writeObject(_southViewDescriptor);
            output.writeObject(_westViewDescriptor);
        }
    }
}