/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.jspresso.framework.model.descriptor {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.jspresso.framework.model.descriptor.EDateType")]
    public class EDateType extends Enum {

        public static const DATE:EDateType = new EDateType("DATE", _);
        public static const DATE_TIME:EDateType = new EDateType("DATE_TIME", _);

        function EDateType(value:String = null, restrictor:* = null) {
            super((value || DATE.name), restrictor);
        }
        
        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [DATE, DATE_TIME];
        }

        public static function valueOf(name:String):EDateType {
        	return EDateType(DATE.constantOf(name));
        }
    }
}