/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (ICollectionDescriptor.as).
 */

package org.jspresso.framework.model.descriptor {

    public interface ICollectionDescriptorBase extends IModelDescriptor {

        function get collectionInterface():Class;

        function get elementDescriptor():IComponentDescriptor;
    }
}