/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (ICollectionPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor {

    import mx.collections.ListCollectionView;

    public interface ICollectionPropertyDescriptorBase extends IRelationshipEndPropertyDescriptor {

        function get manyToMany():Boolean;

        function get orderingProperties():ListCollectionView;

        function get referencedDescriptor():ICollectionDescriptor;
    }
}