/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IComponentDescriptor.as).
 */

package org.jspresso.framework.model.descriptor {

    import mx.collections.ListCollectionView;
    import org.jspresso.framework.util.descriptor.IIconDescriptor;

    public interface IComponentDescriptorBase extends IModelDescriptor, IIconDescriptor {

        function get componentContract():Class;

        function get computed():Boolean;

        function get declaredPropertyDescriptors():ListCollectionView;

        function get entity():Boolean;

        function get lifecycleInterceptors():ListCollectionView;

        function get orderingProperties():ListCollectionView;

        function get propertyDescriptors():ListCollectionView;

        function get purelyAbstract():Boolean;

        function get queryComponentContract():Class;

        function get queryableProperties():ListCollectionView;

        function get renderedProperties():ListCollectionView;

        function get serviceContracts():ListCollectionView;

        function get toStringProperty():String;

        function get unclonedProperties():ListCollectionView;
    }
}