/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IEnumerationPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor {

    import mx.collections.ListCollectionView;

    public interface IEnumerationPropertyDescriptorBase extends IScalarPropertyDescriptor {

        function get enumerationName():String;

        function get enumerationValues():ListCollectionView;

        function get maxLength():Number;

        function get translated():Boolean;
    }
}