/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IModelDescriptor.as).
 */

package org.jspresso.framework.model.descriptor {

    import org.jspresso.framework.util.descriptor.IDescriptor;

    public interface IModelDescriptorBase extends IDescriptor {

        function get modelType():Class;
    }
}