/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor {

    import mx.collections.ListCollectionView;

    public interface IPropertyDescriptorBase extends IModelDescriptor {

        function get delegateClass():Class;

        function get delegateClassName():String;

        function get integrityProcessors():ListCollectionView;

        function get mandatory():Boolean;

        function get modifiable():Boolean;

        function get overload():Boolean;

        function get queryable():Boolean;

        function get readOnly():Boolean;

        function get readabilityGates():ListCollectionView;

        function get unicityScope():String;

        function get writabilityGates():ListCollectionView;
    }
}