/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IReferencePropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor {

    import org.granite.collections.IMap;

    public interface IReferencePropertyDescriptorBase extends IRelationshipEndPropertyDescriptor {

        function get initializationMapping():IMap;

        function get referencedDescriptor():IComponentDescriptor;
    }
}