/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IRelationshipEndPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor {

    public interface IRelationshipEndPropertyDescriptorBase extends IPropertyDescriptor {

        function get composition():Boolean;

        function set reverseRelationEnd(value:IRelationshipEndPropertyDescriptor):void;
        function get reverseRelationEnd():IRelationshipEndPropertyDescriptor;
    }
}