/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (IStringPropertyDescriptor.as).
 */

package org.jspresso.framework.model.descriptor {

    public interface IStringPropertyDescriptorBase extends IScalarPropertyDescriptor {

        function get maxLength():Number;

        function get regexpPattern():String;

        function get regexpPatternSample():String;

        function get upperCase():Boolean;
    }
}